version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: my_backend
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["npm", "run", "dev"]
